# Generated by Django 5.0.6 on 2024-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambiador',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=15)),
                ('edad', models.PositiveSmallIntegerField()),
                ('contrasenia', models.CharField(default='hola', max_length=30)),
            ],
        ),
    ]
