# Generated by Django 5.0.6 on 2024-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayudante',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=15)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='contrasenia',
            field=models.CharField(max_length=30),
        ),
    ]
