# Generated by Django 5.0.6 on 2024-05-17 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0002_ayudante_alter_intercambiador_contrasenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_categoria', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id_filial', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_filial', models.CharField(max_length=50)),
                ('direccion_filial', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ayudante',
            name='dni',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='dni',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo_publicacion', models.CharField(max_length=30)),
                ('descripcion_publicacion', models.CharField(max_length=280)),
                ('imagen_publicacion', models.ImageField(upload_to='fotos/')),
                ('categoria_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar_intercambiador.categoria')),
                ('filial_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar_intercambiador.filial')),
            ],
        ),
    ]
