# Generated by Django 5.0.6 on 2024-05-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0004_alter_ayudante_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudante',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ayudante',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ayudante',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='correo',
            field=models.EmailField(max_length=15),
        ),
    ]
