# Generated by Django 5.0.6 on 2024-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registrar_intercambiador', '0005_ayudante_is_active_ayudante_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudante',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='ayudante_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='ayudante',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='ayudante',
            name='password',
            field=models.CharField(default='caca', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ayudante',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='ayudante_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
