# Generated by Django 5.0.6 on 2024-05-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0007_alter_ayudante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudante',
            name='correo',
            field=models.EmailField(max_length=15, unique=True),
        ),
    ]
