# Generated by Django 5.0.6 on 2024-05-17 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registrar_intercambiador', '0008_alter_ayudante_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercambiador',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen_publicacion',
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='estado',
            field=models.CharField(choices=[('suspendido', 'Suspendido'), ('activo', 'Activo')], default='activo', max_length=15),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='intercambiador_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='password',
            field=models.CharField(default='caca', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='intercambiador_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
