# Generated by Django 5.0.6 on 2024-05-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0009_remove_intercambiador_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiador',
            name='correo',
            field=models.EmailField(max_length=15, unique=True),
        ),
    ]
