# Generated by Django 5.0.6 on 2024-05-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0010_alter_intercambiador_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercambiador',
            name='contrasenia',
        ),
    ]
