# Generated by Django 5.0.6 on 2024-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0011_remove_intercambiador_contrasenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambiador',
            name='contrasenia',
            field=models.CharField(default='caca', max_length=30),
            preserve_default=False,
        ),
    ]
