# Generated by Django 5.0.6 on 2024-05-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0012_intercambiador_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudante',
            name='dni',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
