# Generated by Django 5.0.6 on 2024-05-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0013_alter_ayudante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudante',
            name='dni',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='dni',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
