# Generated by Django 5.0.6 on 2024-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0015_alter_ayudante_dni_alter_intercambiador_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudante',
            name='dni',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='dni',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
