# Generated by Django 5.0.6 on 2024-05-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0016_alter_ayudante_dni_alter_intercambiador_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelado', 'Cancelado')], default='activa', max_length=15),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_publicacion',
            field=models.ImageField(default='../static/logo.png', upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario_publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar_intercambiador.intercambiador'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('texto', models.CharField(max_length=280)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar_intercambiador.publicacion')),
                ('usuario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar_intercambiador.intercambiador')),
            ],
        ),
    ]
