# Generated by Django 5.0.6 on 2024-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0017_publicacion_estado_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambiador',
            name='fecha_suspension',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
