# Generated by Django 5.0.6 on 2024-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0018_intercambiador_fecha_suspension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiador',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
