# Generated by Django 5.0.6 on 2024-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0020_intercambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.CharField(choices=[('activa', 'Activa'), ('ofertada', 'Ofertada'), ('cancelado', 'Cancelado')], default='activa', max_length=15),
        ),
    ]
