# Generated by Django 5.0.6 on 2024-05-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0021_alter_publicacion_estado_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.CharField(choices=[('activa', 'Activa'), ('ofertada', 'Ofertada'), ('pendiente', 'Pendiente')], default='activa', max_length=15),
        ),
    ]
