# Generated by Django 5.0.6 on 2024-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0024_ayudante_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.CharField(choices=[('activa', 'Activa'), ('pendiente', 'Pendiente')], default='activa', max_length=15),
        ),
    ]
