# Generated by Django 5.0.6 on 2024-06-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0027_alter_intercambiador_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiador',
            name='imagen_perfil',
            field=models.ImageField(default='./static/perfil_default.jpg', upload_to=''),
        ),
    ]
