# Generated by Django 5.0.6 on 2024-06-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0029_ayudante_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudante',
            name='imagen_perfil',
            field=models.ImageField(default='../static/perfil_default.jpg', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='imagen_perfil',
            field=models.ImageField(default='../static/perfil_default.jpg', upload_to='fotos/'),
        ),
    ]
