# Generated by Django 5.0.6 on 2024-06-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0030_alter_ayudante_imagen_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudante',
            name='imagen_perfil',
            field=models.ImageField(default='perfil_default.jpg', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='imagen_perfil',
            field=models.ImageField(default='perfil_default.jpg', upload_to='fotos/'),
        ),
    ]
