# Generated by Django 5.0.6 on 2024-06-09 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0031_alter_ayudante_imagen_perfil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_comentario']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='texto_comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
        migrations.AddField(
            model_name='comentario',
            name='es_respuesta_a_comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar_intercambiador.comentario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion_comentario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='registrar_intercambiador.publicacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='dni',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen_publicacion',
            field=models.ImageField(default='../static/logo.png', upload_to='media/fotos'),
        ),
    ]
