# Generated by Django 5.0.6 on 2024-06-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0032_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.CharField(choices=[('activa', 'Activa'), ('pendiente', 'Pendiente'), ('intercambiada', 'Intercambiada')], default='activa', max_length=15),
        ),
    ]
