# Generated by Django 5.0.6 on 2024-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_intercambiador', '0033_alter_publicacion_estado_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='razon_cancelacion',
            field=models.CharField(default='', max_length=280),
        ),
    ]
